version: 0.2
phases:
install:
    runtime-versions:
      nodejs: 16
build:
  commands:    
    build:
      - npm run build                                
run:                              
  command: npm run start